version: '3.8'

services:
  llm-server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: llm-server:latest
    container_name: llm-server
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - /tmp/models:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0,1,2,3
    security_opt:
      - label:disable
    cap_add:
      - SYS_ADMIN
    privileged: true
    network_mode: host
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    tmpfs:
      - /tmp
      - /run
      - /var/run
