version: '3.8'

services:
  llm-server:
    build: .
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - /tmp/models:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0,1,2,3
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    privileged: true
    network_mode: host
    security_opt:
      - seccomp=unconfined
